config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :logout_path
  end

  resources :clochers do
    collection do
      get 'planning'
    end
  end
  resources :transactions, except: :new do
    collection do
      get 'messe'
      get 'don'
      get 'don_messe'
    end
  end

  resources :donnateurs

  resources :morts do 
    member do
      get 'historique'
    end
    collection do 
      get 'top20'
    end
  end
  

  root 'welcome#index'
end

app/models/donnateur.rb
class Donnateur < ApplicationRecord
  before_save :cap
  
  def to_s
    "#{self.nom} #{self.prenom}"
  end
  
    private
  # gere les maj min pour les noms prenoms
  def cap
    self.nom=self.nom.upcase
    self.prenom=self.prenom.capitalize
  end
end

app/controllers/donnateurs_controller.rb
class DonnateursController < ApplicationController
  before_action :set_donnateur, only: [:show, :edit, :update, :destroy]

  # GET /donnateurs
  # GET /donnateurs.json
  def index
    @donnateurs = Donnateur.order(:nom).all
  end

  # GET /donnateurs/1
  # GET /donnateurs/1.json
  def show
  end

  # GET /donnateurs/new
  def new
    @donnateur = Donnateur.new
  end

  # GET /donnateurs/1/edit
  def edit
  end

  # POST /donnateurs
  # POST /donnateurs.json
  def create
    @donnateur = Donnateur.new(donnateur_params)

    respond_to do |format|
      if @donnateur.save
        format.html { redirect_to @donnateur, notice: 'Donnateur was successfully created.' }
        format.json { render :show, status: :created, location: @donnateur }
      else
        format.html { render :new }
        format.json { render json: @donnateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donnateurs/1
  # PATCH/PUT /donnateurs/1.json
  def update
    respond_to do |format|
      if @donnateur.update(donnateur_params)
        format.html { redirect_to @donnateur, notice: 'Donnateur was successfully updated.' }
        format.json { render :show, status: :ok, location: @donnateur }
      else
        format.html { render :edit }
        format.json { render json: @donnateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donnateurs/1
  # DELETE /donnateurs/1.json
  def destroy
    @donnateur.destroy
    respond_to do |format|
      format.html { redirect_to donnateurs_url, notice: 'Donnateur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donnateur
      @donnateur = Donnateur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donnateur_params
      params.require(:donnateur).permit(:nom, :prenom, :adresse_1, :adresse_2, :code_postal, :ville, :telephone)
    end
end

app/views/donnateurs/_form.html.erb
<%= simple_form_for(@donnateur) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :prenom %>
    <%= f.input :adresse_1 %>
    <%= f.input :adresse_2 %>
    <%= f.input :code_postal %>
    <%= f.input :ville %>
    <%= f.input :telephone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: ['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/donnateurs/edit.html.erb
<h1>Editing donnateur</h1>

<%= render 'form' %>

<%= link_to 'Show', @donnateur %> |
<%= link_to 'Back', donnateurs_path %>

app/views/donnateurs/index.html.erb
<h1>Listing donnateurs</h1>

<a href="<%= new_donnateur_path %>" class="btn btn-success" role="button">Nouveau Donnateur</a>

<table class='table'>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Adresse 1</th>
      <th>Adresse 2</th>
      <th>Code postal</th>
      <th>Ville</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donnateurs.each do |donnateur| %>
      <tr>
        <td><%= donnateur.nom %></td>
        <td><%= donnateur.prenom %></td>
        <td><%= donnateur.adresse_1 %></td>
        <td><%= donnateur.adresse_2 %></td>
        <td><%= donnateur.code_postal %></td>
        <td><%= donnateur.ville %></td>
        <td><%= donnateur.telephone %></td>
        <td><%= link_to 'Montrer', donnateur %></td>
        <td><%= link_to 'Editer', edit_donnateur_path(donnateur) %></td>
        <td><%= link_to 'Supprimer', donnateur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="<%= new_donnateur_path %>" class="btn btn-success" role="button">Nouveau Donnateur</a>

app/views/donnateurs/new.html.erb
<h1>New donnateur</h1>

<%= render 'form' %>

<%= link_to 'Back', donnateurs_path %>

app/views/donnateurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @donnateur.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @donnateur.prenom %>
</p>

<p>
  <strong>Adresse 1:</strong>
  <%= @donnateur.adresse_1 %>
</p>

<p>
  <strong>Adresse 2:</strong>
  <%= @donnateur.adresse_2 %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= @donnateur.code_postal %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @donnateur.ville %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @donnateur.telephone %>
</p>

<%= link_to 'Editer', edit_donnateur_path(@donnateur) %> |
<%= link_to 'Retour', donnateurs_path %>