config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :logout_path
  end

  resources :clochers do
    collection do
      get 'planning'
    end
  end
  resources :transactions, except: :new do
    collection do
      get 'messe'
      get 'don'
      get 'don_messe'
    end
  end

  resources :donnateurs

  resources :morts do 
    member do
      get 'historique'
    end
    collection do 
      get 'top20'
    end
  end
  

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @top5=Mort.top_10_libre
  end
end

app/views/welcome/index.html.erb
<h1>Bienvenue !</h1>
<div class='row'>
	<div class='col-md-6'>
		<div class="panel panel-primary">
		  <div class="panel-heading">
			<h3 class="panel-title">Demander une messe</h3>
		  </div>
		  <div class="panel-body">
			Utilisez le bouton ci dessous pour plannifier une messe sur une paroisse<br/><br/>
			<a href="<%= don_messe_transactions_path %>" class="btn btn-success" role="button">Donner une nouvelle messe</a> <a href="<%= messe_transactions_path %>" class="btn btn-success" role="button">Décompter une messe</a>
		  </div>
		</div>
	</div>
	<div class='col-md-6'>
		<div class="panel panel-primary">
		  <div class="panel-heading">
			<h3 class="panel-title">Enregistrer un don</h3>
		  </div>
		  <div class="panel-body">
			Utilisez le bouton ci dessous pour enregistrer un don d'une ou plusieurs messes<br/><br/>
			<a href="<%= don_transactions_path %>" class="btn btn-success" role="button">Enregistrer un don</a>
		  </div>
		</div>
	</div>
</div>
<div class='row'>
	<div class='col-md-6'>
		<div class="panel panel-primary">
		  <div class="panel-heading">
			<h3 class="panel-title">Consulter le planning</h3>
		  </div>
		  <div class="panel-body">
			Utilisez le bouton ci dessous pour consulter le planning des prochaines messes<br/><br/>
			<a href="<%= planning_clochers_path %>" class="btn btn-success" role="button">Consulter le planning</a>
		  </div>
		</div>
	</div>
	<div class='col-md-6'>
		<div class="panel panel-primary">
		  <div class="panel-heading">
			<h3 class="panel-title">Consulter les soldess</h3>
		  </div>
		  <div class="panel-body">
			Utilisez le bouton ci dessous pour consulter les soldes<br/><br/>
			<a href="<%= morts_path %>" class="btn btn-success" role="button">Consulter les soldes</a>
		  </div>
		</div>
	</div>
</div>
<div class='row'>
	<div class='col-md-12'>
		<div class="panel panel-primary">
		  <div class="panel-heading">
			<h3 class="panel-title">TOP 10 des soldes avec planification libre</h3>
		  </div>
		  <div class="panel-body">
			<table class='table'>
			  <thead>
				<tr>
				  <th>Nom</th>
				  <th>Prenom</th>
				  <th>Solde</th>
				  <th>Planification Libre</th>
				  <th>Derniere Transaction</th>
				</tr>
			  </thead>

			  <tbody>
				<% @top5.each do |mort| %>
				  <tr>
					<td><%= mort.nom %></td>
					<td><%= mort.prenom %></td>
					<td><span class="badge"><%= mort.solde %></span></td>
					<td><span class="glyphicon glyphicon-<%= mort.planification_libre ? "ok" : "remove"  %>"> </span></td>
					<td><%= mort.derniere_transaction.nil? ? '-' : l((mort.derniere_transaction.is_a? String) ? Date.parse(mort.derniere_transaction) : mort.derniere_transaction) %></td>
				  </tr>
				<% end %>
			  </tbody>
			</table>
		  </div>
		</div>
	</div>
</div>