config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :logout_path
  end

  resources :clochers do
    collection do
      get 'planning'
    end
  end
  resources :transactions, except: :new do
    collection do
      get 'messe'
      get 'don'
      get 'don_messe'
    end
  end

  resources :donnateurs

  resources :morts do 
    member do
      get 'historique'
    end
    collection do 
      get 'top20'
    end
  end
  

  root 'welcome#index'
end

app/models/clocher.rb
class Clocher < ApplicationRecord
  has_many :transactions, ->{ where("date_effet between ? and ? and montant<=0", Time.now, Time.now + 1.month).order(date_effet: :asc)},  dependent: :destroy
  has_many :morts
  
  def to_s
    self.nom
  end
end

app/controllers/clochers_controller.rb
class ClochersController < ApplicationController
  before_action :set_clocher, only: [:show, :edit, :update, :destroy]

  # GET /clochers
  # GET /clochers.json
  def index
    @clochers = Clocher.all
  end
  
  # GET /clochers/planning
  # GET /clochers/planning.json
  def planning
    @clochers = Clocher.includes(transactions: [:mort]).references(:transactions, :morts).order("clochers.nom, date_effet ASC")
  end


  # GET /clochers/1
  # GET /clochers/1.json
  def show
  end

  # GET /clochers/new
  def new
    @clocher = Clocher.new
  end

  # GET /clochers/1/edit
  def edit
  end

  # POST /clochers
  # POST /clochers.json
  def create
    @clocher = Clocher.new(clocher_params)

    respond_to do |format|
      if @clocher.save
        format.html { redirect_to @clocher, notice: 'Clocher was successfully created.' }
        format.json { render :show, status: :created, location: @clocher }
      else
        format.html { render :new }
        format.json { render json: @clocher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clochers/1
  # PATCH/PUT /clochers/1.json
  def update
    respond_to do |format|
      if @clocher.update(clocher_params)
        format.html { redirect_to @clocher, notice: 'Clocher was successfully updated.' }
        format.json { render :show, status: :ok, location: @clocher }
      else
        format.html { render :edit }
        format.json { render json: @clocher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clochers/1
  # DELETE /clochers/1.json
  def destroy
    @clocher.destroy
    respond_to do |format|
      format.html { redirect_to clochers_url, notice: 'Clocher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clocher
      @clocher = Clocher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clocher_params
      params.require(:clocher).permit(:nom)
    end
end

app/views/clochers/_form.html.erb
<%= simple_form_for(@clocher) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <%= f.input :nom %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: ['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/clochers/edit.html.erb
<h1>Editer clocher</h1>

<%= render 'form' %>

<%= link_to 'Montrer', @clocher %> |
<%= link_to 'Retour', clochers_path %>

app/views/clochers/index.html.erb
<h1>Liste des clochers</h1>

<table class='table'>
  <thead>
    <tr>
	 <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clochers.each do |clocher| %>
      <tr>
		<td><%= clocher.nom %></td>
        <td><%= link_to 'Montrer', clocher %></td>
        <td><%= link_to 'Editer', edit_clocher_path(clocher) %></td>
        <td><%= link_to 'Supprimer', clocher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="<%= new_clocher_path %>" class="btn btn-success" role="button">Nouveau Clocher</a><BR>

app/views/clochers/new.html.erb
<h1>Nouveau clocher</h1>

<%= render 'form' %>

<%= link_to 'Retour', clochers_path %>

app/views/clochers/planning.html.erb
<h1>Planning sur un mois</h1>
<% for clocher in @clochers %>
<div class='row'>
	<div class="panel panel-primary">
	  <div class="panel-heading">
		<h3 class="panel-title"><%= clocher.nom%></h3>
	  </div>
	  <div class="panel-body">
		<table class='table'>
			<thead>
				<tr>
					<th>Date de la messe</th>
					<th>Personne d&eacute;c&eacute;d&eacute;e</th>
					<th>Comentaire/intention diverses</th>
				</tr>
			</thead>
			<tbody>
				<% for messe in clocher.transactions %>
					<tr>
						<td><%= messe.date_effet.nil? ? '-' : l(messe.date_effet)%></td>
						<td><%= messe.mort.to_s %></td>
						<td><%= messe.commentaire %></td>
					</tr>
				<%end%>
			</tbody>
		</table>
	  </div>
	</div>
</div>
<%end%>
<br/>
<%= link_to 'Retour', clochers_path %>

app/views/clochers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @clocher.nom %>
</p>
<%= link_to 'Editer', edit_clocher_path(@clocher) %> |
<%= link_to 'Retour', clochers_path %>