config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :logout_path
  end

  resources :clochers do
    collection do
      get 'planning'
    end
  end
  resources :transactions, except: :new do
    collection do
      get 'messe'
      get 'don'
      get 'don_messe'
    end
  end

  resources :donnateurs

  resources :morts do 
    member do
      get 'historique'
    end
    collection do 
      get 'top20'
    end
  end
  

  root 'welcome#index'
end

app/models/mort.rb
class Mort < ApplicationRecord
  has_many :transactions
  belongs_to :clocher
  before_save :cap
  
  def to_s
    "#{self.nom} #{self.prenom} #{self.prenom2}"
  end
  
  def self.all_with_total
    joins('LEFT OUTER JOIN transactions on morts.id=transactions.mort_id')
      .joins('LEFT OUTER JOIN clochers on morts.clocher_id=clochers.id')
      .select('morts.id, clochers.nom as nom_clocher, morts.nom, prenom, prenom2, date_de_deces, sum(transactions.montant) as solde, planification_libre')
      .group('morts.id', :nom_clocher, 'clochers.nom','morts.nom', :prenom, :prenom2, :date_de_deces, :planification_libre)
      .order('clochers.nom ASC',  'nom'=> :asc)
  end
  
  def self.top_oldest(nb)
    joins('LEFT OUTER JOIN transactions on morts.id=transactions.mort_id')
      .select('morts.id, morts.nom, prenom, prenom2, date_de_deces, sum(transactions.montant) as solde, max(transactions.date_effet) as derniere_transaction, planification_libre')
      .group('morts.id', 'morts.nom', :prenom, :prenom2, :date_de_deces, :planification_libre)
      .having("max(transactions.date_effet)< ?",  Time.now - 2.month)
      .order('sum(transactions.montant) desc' )
      .first(nb)
  end
  
  def self.top_10_libre
    joins('LEFT OUTER JOIN transactions on morts.id=transactions.mort_id')
      .select('morts.id, morts.nom, prenom, date_de_deces, sum(transactions.montant) as solde, max(transactions.date_effet) as derniere_transaction, planification_libre')
      .group('morts.id', 'morts.nom', :prenom, :date_de_deces, :planification_libre)
      .where(planification_libre: true)
      .order('sum(transactions.montant) desc' )
      .first(10)
  end
  
  private
  # gere les maj min pour les noms prenoms
  def cap
    self.nom=self.nom.upcase
    self.prenom=self.prenom.capitalize
    self.prenom2=self.prenom2.capitalize
  end
end

app/controllers/morts_controller.rb
class MortsController < ApplicationController
  before_action :set_mort, only: [:show, :edit, :update, :destroy, :historique]

  # GET /morts
  # GET /morts.json
  def index
    @morts = Mort.all_with_total
    # render plain: Mort.top5_oldest
  end

  # GET /morts/1
  # GET /morts/1.json
  def show
  end

  # GET /morts/new
  def new
    @mort = Mort.new
  end

  # GET /morts/1/edit
  def edit
  end

  # GET /morts/1/historique
  def historique
    @transactions=@mort.transactions
    render 'transactions/index.html'
  end
  
  # GET /morts/top20
  def top20
    @morts=Mort.top_oldest(20)
  end
  
  # POST /morts
  # POST /morts.json
  def create
    @mort = Mort.new(mort_params)

    respond_to do |format|
      if @mort.save
        format.html { redirect_to @mort, notice: 'Mort was successfully created.' }
        format.json { render :show, status: :created, location: @mort }
      else
        format.html { render :new }
        format.json { render json: @mort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morts/1
  # PATCH/PUT /morts/1.json
  def update
    respond_to do |format|
      if @mort.update(mort_params)
        format.html { redirect_to @mort, notice: 'Mort was successfully updated.' }
        format.json { render :show, status: :ok, location: @mort }
      else
        format.html { render :edit }
        format.json { render json: @mort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /morts/1
  # DELETE /morts/1.json
  def destroy
    @mort.destroy
    respond_to do |format|
      format.html { redirect_to morts_url, notice: 'Mort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mort
      @mort = Mort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mort_params
      params.require(:mort).permit(:nom, :prenom, :prenom2, :date_de_deces, :clocher_id, :planification_libre)
    end
end

app/views/morts/_form.html.erb
<%= simple_form_for(@mort) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :prenom %>
    <%= f.input :prenom2 %>
    <%= f.input :date_de_deces %>
    <%= f.input :planification_libre %>
	<%= f.association :clocher %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: ['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/morts/edit.html.erb
<h1>Edition de la personne  d&eacute;c&eacute;d&eacute;e</h1>

<%= render 'form' %>

<%= link_to 'Montrer', @mort %> |
<%= link_to 'Retour', morts_path %>

app/views/morts/index.html.erb
<h1>Liste des personnes d&eacute;c&eacute;d&eacute;es</h1>

<a href="<%= new_mort_path %>" class="btn btn-success" role="button">Nouvelle personne  décédée</a><BR>
<% clocher="" %>
<% @morts.each do |mort| %>
<% if mort.nom_clocher != clocher %>
<% if clocher!="" %><%# closes previous table %>
  </tbody>
</table>
</div>
</div>
<%end%>
<div class="panel panel-primary">
		  <div class="panel-heading">
			<h3 class="panel-title"><%= mort.nom_clocher%></h3>
		  </div>
		  <div class="panel-body">
<table class='table'>
  <thead>
    <tr>
      <th>Clocher</th>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Prenom2</th>
      <th>Date de deces</th>
      <th>Solde</th>
      <th>Planification libre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<%end%>
<% clocher= mort.nom_clocher %>
      <tr>
        <td><%= mort.nom_clocher %></td>
        <td><%= mort.nom %></td>
        <td><%= mort.prenom %></td>
        <td><%= mort.prenom2 %></td>
        <td><%= mort.date_de_deces.nil? ? '-' : l(mort.date_de_deces) %></td>
        <td><span class="badge"><%= mort.solde %></span></td>
        <td><span class="glyphicon glyphicon-<%= mort.planification_libre ? "ok" : "remove"  %>"> </span></td>
		<td><%= link_to 'Historique', historique_mort_path(mort) %>
        <td><%= link_to 'Montrer', mort %></td>
        <td><%= link_to 'Editer', edit_mort_path(mort) %></td>
        <td><%= link_to 'Supprimer', mort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>
<br>


<a href="<%= new_mort_path %>" class="btn btn-success" role="button">Nouvelle personne  décédée</a>

app/views/morts/new.html.erb
<h1>Nouvelle personne  d&eacute;c&eacute;d&eacute;e</h1>

<%= render 'form' %>

<%= link_to 'Back', morts_path %>

app/views/morts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @mort.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @mort.prenom %>
</p>

<p>
  <strong>Prenom2:</strong>
  <%= @mort.prenom2 %>
</p>

<p>
  <strong>Date de deces:</strong>
  <%= @mort.date_de_deces %>
</p>
<p>
  <strong>Planification libre:</strong>
  <%= @mort.planification_libre ? "OUI" : "NON" %>
</p>

<%= link_to 'Editer', edit_mort_path(@mort) %> |
<%= link_to 'Retour', morts_path %>

app/views/morts/top20.html.erb
<h1>Liste des personnes d&eacute;c&eacute;d&eacute;es</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Prenom2</th>
      <th>Date de deces</th>
      <th>Solde</th>
      <th>Planification libre</th>
      <th>Dernière transaction</th>
    </tr>
  </thead>

  <tbody>
    <% @morts.each do |mort| %>
      <tr>
        <td><%= mort.nom %></td>
        <td><%= mort.prenom %></td>
        <td><%= mort.prenom2 %></td>
        <td><%= mort.date_de_deces.nil? ? '-' : l(mort.date_de_deces) %></td>
        <td><span class="badge"><%= mort.solde %></span></td>
		<td><span class="glyphicon glyphicon-<%= mort.planification_libre ? "ok" : "remove"  %>"> </span></td>
        <td><%= mort.derniere_transaction.nil? ? '-' : mort.derniere_transaction %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="<%= messe_transactions_path %>" class="btn btn-success" role="button">Décompter une messe</a>